window.ATK_AUTO_IMAGE_MAP = window.ATK_AUTO_IMAGE_MAP || {
    "4fd2e261ba6b4d9fa287e70ebd69eaa9": "4fd2e261-ba6b-4d9f-a287-e70ebd69eaa9.jpeg",
    "amplopcoklata3": "Amplop Coklat A3.jpg",
    "amplopcoklata4": "Amplop Coklat A4.jpg",
    "amplopcoklatfolio": "Amplop Coklat Folio.jpg",
    "amplopputih": "Amplop Putih.jpg",
    "amplopputiha4": "Amplop Putih A4.jpg",
    "bindera4": "Binder A4.jpg",
    "bindera5": "Binder A5.jpg",
    "bindercliplarge": "Binder Clip Large.jpg",
    "binderclipmedium": "Binder Clip Medium.jpeg",
    "binderclipsmall": "Binder Clip Small.jpeg",
    "bukuagenda": "Buku Agenda.jpg",
    "bukuekspedisi": "Buku Ekspedisi.png",
    "bukugambar": "Buku Gambar.jpeg",
    "bukugambara3": "Buku Gambar A3.jpeg",
    "bukugambara4": "Buku Gambar A4.jpg",
    "bukugambara5": "Buku Gambar A5.jpg",
    "bukugambarsketsa": "Buku Gambar Sketsa.jpeg",
    "bukukas": "Buku Kas.jpg",
    "bukukegiatan": "Buku Kegiatan.jpg",
    "bukukotakkotak": "Buku Kotak-Kotak.jpeg",
    "bukumusik": "Buku Musik.jpeg",
    "bukutulis": "Buku Tulis.jpeg",
    "bukutulis100lembar": "Buku Tulis 100 Lembar.jpg",
    "bukutulis38lembar": "Buku Tulis 38 Lembar.jpg",
    "bukutulis58lembar": "Buku Tulis 58 Lembar.jpg",
    "busurderajat": "Busur Derajat.jpg",
    "carbonlessform": "Carbonless Form.jpg",
    "catair": "Cat Air.jpeg",
    "cd": "CD.png",
    "chatgptimage20sep2026162940": "ChatGPT Image 20 Sep 2026, 16.29.40.png",
    "clearholder": "Clear Holder.jpeg",
    "clipboard": "Clipboard.jpeg",
    "correctionfluid": "Correction Fluid.jpeg",
    "correctionpen": "Correction Pen.jpg",
    "correctiontape": "Correction Tape.jpeg",
    "crayon": "Crayon.jpeg",
    "crayon12warna": "Crayon 12 Warna.jpg",
    "crayon24warna": "Crayon 24 Warna.jpg",
    "cutterbesar": "Cutter Besar.jpeg",
    "cutterkecil": "Cutter Kecil.jpg",
    "dispensertape": "Dispenser Tape.jpg",
    "doubletape": "Double Tape.jpeg",
    "doubletip12inch": "Double Tip 1,2 Inch.jpeg",
    "doubletipfoam": "Double Tip Foam.jpg",
    "drawingpen": "Drawing-Pen.jpeg",
    "expandingfile": "Expanding File.jpg",
    "flashdisk": "Flashdisk.png",
    "foamsheet": "Foam Sheet.jpg",
    "folder": "Folder.jpeg",
    "fotocopy": "fotocopy.jpeg",
    "glittercraft": "Glitter Craft.jpeg",
    "guntingbesar": "Gunting Besar.jpeg",
    "guntingkecil": "Gunting Kecil.jpeg",
    "highlighterset": "Highlighter Set.jpg",
    "hvsa470gsm": "HVS A4 70 gsm.jpg",
    "hvsa480gsm": "HVS A4 80 gsm.jpeg",
    "hvsf470gsm": "HVS F4 70 gsm.jpeg",
    "hvsf480gsm": "HVS F4 80 gsm.jpg",
    "idcard": "ID Card.jpg",
    "isicutterbesar": "Isi Cutter Besar.jpeg",
    "isicutterkecil": "Isi Cutter Kecil.jpeg",
    "isipensilmekanik": "Isi Pensil Mekanik.jpeg",
    "isistaples2310": "Isi Staples 23-10.jpg",
    "isistaples236": "Isi Staples 23-6.jpg",
    "isistaples24": "Isi Staples 24.jpeg",
    "isistaplesno10": "Isi Staples No.10.jpeg",
    "isolasilistrik": "Isolasi Listrik.jpeg",
    "jangka": "Jangka.jpg",
    "jiliddokumen": "JilidDokumen.jpg",
    "kabeldata": "Kabel Data.jpg",
    "kalkulator": "Kalkulator.jpeg",
    "kartunama": "Kartu Nama.jpg",
    "kertasa3": "Kertas A3.jpg",
    "kertasartcarton": "Kertas Art Carton.png",
    "kertasartpaper": "Kertas Art Paper.jpg",
    "kertasasturo": "Kertas Asturo.jpg",
    "kertasasturofolio": "Kertas Asturo Folio.jpeg",
    "kertasbuffalo": "Kertas Buffalo.png",
    "kertasconcorde": "Kertas Concorde.png",
    "kertascrepe": "Kertas Crepe.jpeg",
    "kertasdrawing": "Kertas Drawing.jpg",
    "kertasfax": "Kertas Fax.jpg",
    "kertasfotoglossy": "Kertas Foto Glossy.jpg",
    "kertasfotomatte": "Kertas Foto Matte.jpg",
    "kertashvswarnaa4": "Kertas HVS Warna A4.jpg",
    "kertashvswarnaf4": "Kertas HVS Warna F4.jpg",
    "kertasivory": "Kertas Ivory.jpg",
    "kertasjasmine": "Kertas Jasmine.jpg",
    "kertaskado": "Kertas Kado.jpg",
    "kertaskalkir": "Kertas Kalkir.jpg",
    "kertaskarbon": "Kertas Karbon.jpg",
    "kertaskarton": "Kertas Karton.jpeg",
    "kertaskartontebal": "Kertas Karton Tebal.jpg",
    "kertaskopi": "Kertas Kopi.jpeg",
    "kertaslinen": "Kertas Linen.png",
    "kertasmanggis": "Kertas Manggis.jpg",
    "kertasmanila": "Kertas Manila.jpeg",
    "kertasmilimeterblock": "Kertas Milimeter Block.jpeg",
    "kertasorigami": "Kertas Origami.jpg",
    "kertasorigamimotif": "Kertas Origami Motif.jpeg",
    "kertasorigamiwarna": "Kertas Origami Warna.jpg",
    "kertassamson": "Kertas Samson.jpg",
    "kertassertifikat": "Kertas Sertifikat.jpg",
    "kertasstickera4": "Kertas Sticker A4.jpg",
    "kertasthermal57mm": "Kertas Thermal 57mm.jpg",
    "kertasthermal80mm": "Kertas Thermal 80mm.jpeg",
    "kertaswarna": "Kertas Warna.jpeg",
    "klipkertaswarna": "Klip Kertas Warna.jpg",
    "kotakpensil": "Kotak Pensil.jpeg",
    "kuaslukis": "Kuas Lukis.jpeg",
    "labelnama": "Label Nama.jpg",
    "labelsticker": "Label Sticker.jpg",
    "lakbanbening": "Lakban Bening.jpeg",
    "lakbanbeningbesar": "Lakban Bening Besar.png",
    "lakbancoklat": "Lakban Coklat.jpeg",
    "lakbanhitam": "Lakban Hitam.jpeg",
    "lakbankertas": "Lakban Kertas.jpeg",
    "lakbanopp": "Lakban OPP.jpg",
    "laminating": "Laminating.jpg",
    "lemglitter": "Lem Glitter.jpeg",
    "lemkayu": "Lem Kayu.jpeg",
    "lemkertas": "Lem Kertas.jpeg",
    "lemkertascair": "Lem Kertas Cair.jpeg",
    "lemserbaguna": "Lem Serbaguna.jpeg",
    "lemstik": "Lem Stik.png",
    "lemtembak": "Lem Tembak.jpeg",
    "mapbusinessfile": "Map Business File.jpg",
    "mapdokumen": "Map Dokumen.jpeg",
    "mapfolio": "Map Folio.jpg",
    "mapkancing": "Map Kancing.jpeg",
    "mapkartunama": "Map Kartu Nama.jpg",
    "mapl": "Map L.jpg",
    "maplamarankerja": "Map Lamaran Kerja.jpeg",
    "mapplastik": "Map Plastik.jpg",
    "mapportofolio": "Map Portofolio.jpg",
    "mapresleting": "Map Resleting.jpeg",
    "mapsertifikat": "Map Sertifikat.jpg",
    "markerboardrefill": "Marker Board Refill.jpg",
    "maskingtape": "Masking Tape.jpg",
    "memopad": "Memo Pad.jpeg",
    "mouse": "Mouse.jpg",
    "mucipreview": "muci-preview.jpg",
    "nota": "Nota.jpeg",
    "notebook": "Notebook.jpg",
    "ordnera4": "Ordner A4.jpeg",
    "paletcat": "Palet Cat.jpeg",
    "papanjalana4": "Papan Jalan A4.png",
    "papantulismini": "Papan Tulis Mini.jpg",
    "paperclip": "Paper Clip.jpeg",
    "pasfoto": "pasfoto.jpeg",
    "penggaris15cm": "Penggaris 15 cm.jpg",
    "penggaris30cm": "Penggaris 30 cm.jpeg",
    "penggarisbesi30cm": "Penggaris Besi 30 cm.jpg",
    "penghapus": "Penghapus.jpeg",
    "penghapuspapantulis": "Penghapus Papan Tulis.jpeg",
    "penghapuspensilwarna": "Penghapus Pensil Warna.jpg",
    "pensil2b": "Pensil2B.jpg",
    "pensilhb": "Pensil HB.jpg",
    "pensilmekanik": "Pensil Mekanik.jpeg",
    "pensilwarna": "Pensil Warna.jpeg",
    "pensilwarna12warna": "Pensil Warna 12 Warna.jpeg",
    "pensilwarna24warna": "Pensil Warna 24 Warna.png",
    "perforator1lubang": "Perforator 1 Lubang.jpg",
    "perforator2lubang": "Perforator 2 Lubang.jpeg",
    "pinbinder": "Pin Binder.jpg",
    "plastikidcard": "Plastik ID Card.jpeg",
    "plastiklaminating": "Plastik Laminating.jpeg",
    "printer": "printer.jpeg",
    "pulpen": "Pulpen.jpg",
    "pulpenballpoint": "Pulpen Ballpoint.jpeg",
    "pulpengel": "Pulpen Gel.jpg",
    "pulpengelballpoint": "PulpenGel&Ballpoint.jpeg",
    "pushpin": "Push Pin.jpeg",
    "rautan2lubang": "Rautan 2 Lubang.jpeg",
    "rautanpensil": "Rautan Pensil.jpg",
    "refillcorrectiontape": "Refill Correction Tape.png",
    "setpenggarisgeometri": "Set Penggaris Geometri.jpeg",
    "sketchbook": "Sketchbook.jpeg",
    "snelhecter": "Snelhecter.jpeg",
    "spidolpermanen": "Spidol Permanen.png",
    "spidolwarna": "Spidol Warna.jpeg",
    "spidolwarna12warna": "Spidol Warna 12 Warna.jpg",
    "spidolwarna24warna": "Spidol Warna 24 Warna.jpg",
    "spidolwhiteboard": "Spidol Whiteboard.jpeg",
    "stabilo": "Stabilo.jpeg",
    "stapler": "Stapler.jpeg",
    "staplermini": "Stapler Mini.jpg",
    "staplesheavyduty": "Staples Heavy Duty.jpg",
    "stempel": "stempel.png",
    "stickernamaanak": "Sticker Nama Anak.jpg",
    "sticklemtembak": "Stick Lem Tembak.jpeg",
    "stickynotes": "Sticky Notes.jpeg",
    "stopmap": "Stopmap.png",
    "taliidcard": "Tali ID Card.jpeg",
    "tempatpensil": "Tempat Pensil.jpeg",
};

// Peta gambar otomatis disinkronkan dari file gambar yang tersedia di repository.
// Renderer katalog tetap berada di index.html.
